/*
 * Name: Sam Dirr
 * Date: September 20, 2026
 * Assignment: CSD 420 Module 8 Assignment 8.2
 * Purpose: Display 10,000 letters, 10,000 digits, and 10,000 symbols,
 *          generated by three threads and appended one character at a time.
 */
import java.util.concurrent.CountDownLatch;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.TextArea;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class SamThreeThreads extends Application {
    public static final int CHARACTERS_PER_THREAD = 10_000;
    private SamCharacterGenerator generator;
    private int displayed;

    /** Creates the text area and starts the three producers. */
    @Override
    public void start(Stage stage) {
        TextArea textArea = new TextArea();
        textArea.setEditable(false);
        textArea.setWrapText(true);
        Label status = new Label("Generating 10,000 characters per thread...");
        BorderPane root = new BorderPane(textArea);
        root.setBottom(status);
        root.setPadding(new Insets(12));
        BorderPane.setMargin(status, new Insets(10, 0, 0, 0));
        stage.setTitle("Sam Dirr - CSD 420 Assignment 8.2");
        stage.setScene(new Scene(root, 850, 550));
        stage.show();

        generator = new SamCharacterGenerator(CHARACTERS_PER_THREAD, character -> {
            CountDownLatch appended = new CountDownLatch(1);
            // JavaFX controls may only be changed on the JavaFX application thread.
            Platform.runLater(() -> {
                try {
                    textArea.appendText(String.valueOf(character));
                    displayed++;
                    if (displayed == 3 * CHARACTERS_PER_THREAD) {
                        status.setText("Complete: 10,000 letters + 10,000 digits + 10,000 symbols = 30,000 characters.");
                    }
                } finally {
                    appended.countDown();
                }
            });
            try {
                // Wait for this append before allowing another character.
                // This prevents a backlog of 30,000 queued UI updates.
                appended.await();
            } catch (InterruptedException interrupted) {
                Thread.currentThread().interrupt();
            }
        });
        generator.start();
    }

    /** Stops waiting workers when the application closes. */
    @Override
    public void stop() {
        if (generator != null) {
            generator.cancel();
        }
    }

    public static void main(String[] args) {
        launch(args);
    }
}
